### PR TITLE
fix(haskell): install Haskell libraries

### PR DESCRIPTION
**Pull request by klezm**
As discussed in devcontainers-contrib/features/issues/584 you can install either executables or libraries with Cabal. This PR fixes devcontainers-contrib/features/issues/584 and adds the option to install libraries besides executables.

### CODE REVIEW

**Comment by klezm** [comment]
Here is the original PR devcontainers-contrib/features/pull/600

**Comment by koralowiec** [comment]
As you introduce a new option to the feature (`globalLibraries`), I would like to have a test scenario for that - It should verify whether the packages are installed as libraries

**Comment by koralowiec** [comment]
Yeah, test passes locally

Indeed, it seems that the issue may be the lack of disk space - 3rd line here ([ref](https://github.com/devcontainers-extra/features/actions/runs/11628741205/job/32384824821?pr=52#step:4:828)):
```
[2024-11-01T11:54:09.389Z] #14 83.60 [ Error ] []8;;[https://errors.haskell.org/messages/GHCup-00080\GHCup](https://errors.haskell.org/messages/GHCup-00080%1B/GHCup)
[2024-11-01T11:54:09.523Z] -00080]8;;\] Failed to merge file tree from /home/vscode/.cache/ghcup/tmp/ghcup-e8a428df65a662cd/home/vscode/.local/share/ghcup/ghc/9.4.8 to /home/vscode/.local/share/ghcup/ghc/9.4.8 
#14 83.60 [ ...   ] exception was: <file descriptor: 18>: hPutBuf: resource exhausted (No space left on device)
#14 83.60 [ ...   ] ...you may need to delete /home/vscode/.local/share/ghcup/ghc/9.4.8 manually. Make sure it's gone.
#14 83.60 [ Error ] Also check the logs in /home/vscode/.cache/ghcup/logs
```

If I understand currently, right now we have 4 different packages set for the scenario ([here](https://github.com/devcontainers-extra/features/pull/52/files#diff-122fc77a0e48ef7104a1f9e0de594d2dc634a07e2009c04c9f6d338f21353083R12)). I think that we can reduce the number to just 2 libraries. Also, can we install more lightweight ones? Maybe that will help reduce the disk usage

**Comment by klezm** [comment]
`hspec` has `QuickCheck` and  `HUnit` besides countless others as dependencies anyways.
For testing it doesn't matter which library I install. So I'll search for one that has minimum dependencies.

To free up space on the action runner I used this action once and it worked fine for me. It also allows filtering for what to delete.
https://github.com/marketplace/actions/free-disk-space-ubuntu

**Comment by koralowiec** [comment]
I check out that GitHub Action! Thanks for suggesting it

**Comment by koralowiec** [comment]
I included the GitHub Action in the Workflow (more context in #69). Could you please rebase your branch?

**Comment by klezm** [comment]
Those are some small Haskell packages we could use for testing. I'll go with `stm` as it is the smallest with no dependencies at all

- [stm](https://hackage.haskell.org/package/stm) no deps
    - `import Control.Concurrent.STM"`
- [HUnit](https://hackage.haskell.org/package/HUnit) deps: call-stack
    - `import Test.HUnit"`
- [QuickCheck](https://hackage.haskell.org/package/QuickCheck) deps: splitmix random
    - `import Test.QuickCheck"`
- [async](https://hackage.haskell.org/package/async) deps: os-string hashable
    - `import Control.Concurrent.Async"`
- [text](https://hackage.haskell.org/package/text) no deps but long build time!
    - `import Data.Text"`

**Review by koralowiec — APPROVED** [review]
Thanks for your contribution! LGTM

**Pull request merged**
